name: Build Book Builder Image

on:
  push:
    branches:
      - main
    paths:
      - 'install/book-builder/**'
      - '.github/workflows/build-book-builder.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./install/book-builder
          push: true
          tags: ghcr.io/flynnty/project-nomad-book-builder:latest
